// examples/angular-demo/src/app/components/issue-detail-demo.component.ts
import { Component, Input, Output, EventEmitter, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HulyIssueDetailComponent } from '@huly-embed/angular';

@Component({
  selector: 'app-issue-detail-demo',
  standalone: true,
  imports: [FormsModule, HulyIssueDetailComponent],
  template: `
    <div class="demo-section">
      <div class="demo-section-header">
        <h2>Issue Detail</h2>
      </div>
      <div class="demo-controls">
        <span class="demo-controls-label">Issue ID</span>
        <input
          type="text"
          [ngModel]="inputValue()"
          (ngModelChange)="inputValue.set($event)"
          (keydown.enter)="loadIssue()"
          placeholder="SUPPO-1"
        />
        <button class="load-btn" (click)="loadIssue()">Load</button>
      </div>
      <div class="embed-container embed-container--auto">
        @if (issueId()) {
          <huly-issue-detail
            [issueId]="issueId()"
            [project]="project"
            [externalUser]="externalUser"
            (resized)="event.emit('issue-detail: resize ' + $event.height + 'px')"
          >
          </huly-issue-detail>
        } @else {
          <div class="empty-state">
            <div class="empty-state-icon">&#x1f50d;</div>
            Enter an issue ID above and press Enter or click Load.
          </div>
        }
      </div>
    </div>
  `,
})
export class IssueDetailDemoComponent {
  @Input() project?: string;
  @Input() externalUser?: string;
  @Output() event = new EventEmitter<string>();

  inputValue = signal('');
  issueId = signal('');

  loadIssue() {
    const value = this.inputValue().trim();
    if (value) {
      this.issueId.set(value);
    }
  }
}

// examples/react-demo/src/components/IssueDetailDemo.tsx
import { useState } from 'react';
import { HulyIssueDetail } from '@huly-embed/react';

interface Props {
  project?: string;
  externalUser?: string;
  onEvent: (message: string) => void;
}

export function IssueDetailDemo({ project, externalUser, onEvent }: Props) {
  const [issueId, setIssueId] = useState('');

  return (
    <div className="demo-section">
      <div className="demo-section-header">
        <h2>Issue Detail</h2>
      </div>
      <div className="demo-controls">
        <span className="demo-controls-label">Issue ID</span>
        <input
          type="text"
          value={issueId}
          onChange={(e) => setIssueId(e.target.value)}
          placeholder="DEMO-1"
        />
      </div>
      <div className="embed-container embed-container--auto">
        {issueId ? (
          <HulyIssueDetail
            issueId={issueId}
            project={project}
            externalUser={externalUser}
            onReady={() => onEvent(`issue-detail: ready (${issueId})`)}
            onResize={(e) => onEvent(`issue-detail: resize ${e.height}px`)}
            onError={(e) => onEvent(`error: ${e.reason}`)}
            loadingContent={<div className="loading-text">Loading issue detail...</div>}
            errorContent={<div className="error-text">Failed to load. Check backend is running.</div>}
          />
        ) : (
          <div className="empty-state">Enter an issue ID above to load the detail view.</div>
        )}
      </div>
    </div>
  );
}
