// examples/angular-demo/src/app/components/more-demo.component.ts
import { Component, Input, Output, EventEmitter, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  HulyMyIssuesComponent,
  HulyMilestonesComponent,
  HulyMilestoneDetailComponent,
  HulyComponentsComponent,
  HulyIssueTemplatesComponent,
  HulyIssuePreviewComponent,
  HulyTimeReportsComponent,
  HulyCreateProjectComponent,
  HulyThreadComponent,
  HulyActivityComponent,
  HulyCalendarComponent,
  HulyBoardComponent,
  HulyDepartmentStaffComponent,
  HulyTodosComponent,
  HulyMyLeadsComponent,
  HulyApplicationsComponent,
} from '@huly-embed/angular';

type MoreView =
  | 'my-issues' | 'board' | 'milestones' | 'milestone-detail'
  | 'components' | 'issue-templates' | 'issue-preview' | 'time-reports'
  | 'create-project' | 'thread' | 'activity' | 'calendar'
  | 'department-staff' | 'todos' | 'my-leads' | 'applications';

interface ViewOption {
  value: MoreView;
  label: string;
}

@Component({
  selector: 'app-more-demo',
  standalone: true,
  imports: [
    FormsModule,
    HulyMyIssuesComponent,
    HulyMilestonesComponent,
    HulyMilestoneDetailComponent,
    HulyComponentsComponent,
    HulyIssueTemplatesComponent,
    HulyIssuePreviewComponent,
    HulyTimeReportsComponent,
    HulyCreateProjectComponent,
    HulyThreadComponent,
    HulyActivityComponent,
    HulyCalendarComponent,
    HulyBoardComponent,
    HulyDepartmentStaffComponent,
    HulyTodosComponent,
    HulyMyLeadsComponent,
    HulyApplicationsComponent,
  ],
  template: `
    <div class="demo-section">
      <div class="demo-section-header">
        <h2>More Components</h2>
      </div>
      <div class="demo-controls">
        <span class="demo-controls-label">Component</span>
        <select [ngModel]="view()" (ngModelChange)="onViewChange($event)">
          @for (v of views; track v.value) {
            <option [value]="v.value">{{ v.label }}</option>
          }
        </select>
        @if (needsId()) {
          <span class="demo-controls-label">{{ idLabel() }}</span>
          <input
            type="text"
            [ngModel]="inputValue()"
            (ngModelChange)="inputValue.set($event)"
            (keydown.enter)="loadEntity()"
            placeholder="Enter ID"
          />
          <button class="load-btn" (click)="loadEntity()">Load</button>
        }
      </div>
      <div class="embed-container">
        @switch (view()) {
          @case ('my-issues') {
            <huly-my-issues
              [project]="project"
              [externalUser]="externalUser"
              (issueSelected)="event.emit('issue-selected: ' + $event.identifier)"
            ></huly-my-issues>
          }
          @case ('board') {
            <huly-board
              [externalUser]="externalUser"
              (issueSelected)="event.emit('board issue-selected: ' + $event.identifier)"
            ></huly-board>
          }
          @case ('milestones') {
            <huly-milestones [project]="project" [externalUser]="externalUser"></huly-milestones>
          }
          @case ('milestone-detail') {
            @if (entityId()) {
              <huly-milestone-detail [milestoneId]="entityId()" [externalUser]="externalUser"></huly-milestone-detail>
            } @else {
              <div class="empty-state">Enter a milestone ID above and click Load.</div>
            }
          }
          @case ('components') {
            <huly-components [project]="project" [externalUser]="externalUser"></huly-components>
          }
          @case ('issue-templates') {
            <huly-issue-templates [project]="project" [externalUser]="externalUser"></huly-issue-templates>
          }
          @case ('issue-preview') {
            @if (entityId()) {
              <huly-issue-preview [issueId]="entityId()" [externalUser]="externalUser"></huly-issue-preview>
            } @else {
              <div class="empty-state">Enter an issue ID above and click Load.</div>
            }
          }
          @case ('time-reports') {
            @if (entityId()) {
              <huly-time-reports [issueId]="entityId()" [externalUser]="externalUser"></huly-time-reports>
            } @else {
              <div class="empty-state">Enter an issue ID above and click Load.</div>
            }
          }
          @case ('create-project') {
            <huly-create-project [externalUser]="externalUser"></huly-create-project>
          }
          @case ('thread') {
            @if (entityId()) {
              <huly-thread [threadId]="entityId()" [externalUser]="externalUser"></huly-thread>
            } @else {
              <div class="empty-state">Enter a thread ID above and click Load.</div>
            }
          }
          @case ('activity') {
            @if (entityId()) {
              <huly-activity [issueId]="entityId()" [externalUser]="externalUser"></huly-activity>
            } @else {
              <div class="empty-state">Enter an issue ID above and click Load.</div>
            }
          }
          @case ('calendar') {
            <huly-calendar [externalUser]="externalUser"></huly-calendar>
          }
          @case ('department-staff') {
            @if (entityId()) {
              <huly-department-staff [departmentId]="entityId()" [externalUser]="externalUser"></huly-department-staff>
            } @else {
              <div class="empty-state">Enter a department ID above and click Load.</div>
            }
          }
          @case ('todos') {
            <huly-todos [externalUser]="externalUser"></huly-todos>
          }
          @case ('my-leads') {
            <huly-my-leads [externalUser]="externalUser"></huly-my-leads>
          }
          @case ('applications') {
            <huly-applications [externalUser]="externalUser"></huly-applications>
          }
        }
      </div>
    </div>
  `,
})
export class MoreDemoComponent {
  @Input() project?: string;
  @Input() externalUser?: string;
  @Output() event = new EventEmitter<string>();

  views: ViewOption[] = [
    { value: 'my-issues', label: 'My Issues' },
    { value: 'board', label: 'Board' },
    { value: 'milestones', label: 'Milestones' },
    { value: 'milestone-detail', label: 'Milestone Detail' },
    { value: 'components', label: 'Components' },
    { value: 'issue-templates', label: 'Issue Templates' },
    { value: 'issue-preview', label: 'Issue Preview' },
    { value: 'time-reports', label: 'Time Reports' },
    { value: 'create-project', label: 'Create Project' },
    { value: 'thread', label: 'Thread' },
    { value: 'activity', label: 'Activity' },
    { value: 'calendar', label: 'Calendar' },
    { value: 'department-staff', label: 'Department Staff' },
    { value: 'todos', label: 'Todos' },
    { value: 'my-leads', label: 'My Leads' },
    { value: 'applications', label: 'Applications' },
  ];

  private readonly ID_VIEWS = new Set<MoreView>([
    'milestone-detail', 'issue-preview', 'time-reports', 'thread', 'activity', 'department-staff',
  ]);

  private readonly ID_LABELS: Record<string, string> = {
    'milestone-detail': 'Milestone ID',
    'issue-preview': 'Issue ID',
    'time-reports': 'Issue ID',
    'thread': 'Thread ID',
    'activity': 'Issue ID',
    'department-staff': 'Department ID',
  };

  view = signal<MoreView>('my-issues');
  inputValue = signal('');
  entityId = signal('');
  needsId = signal(false);
  idLabel = signal('');

  onViewChange(value: MoreView) {
    this.view.set(value);
    this.inputValue.set('');
    this.entityId.set('');
    this.needsId.set(this.ID_VIEWS.has(value));
    this.idLabel.set(this.ID_LABELS[value] ?? '');
  }

  loadEntity() {
    const value = this.inputValue().trim();
    if (value) this.entityId.set(value);
  }
}

// examples/react-demo/src/components/MoreDemo.tsx
import { useState } from 'react';
import {
  HulyMyIssues,
  HulyMilestones,
  HulyMilestoneDetail,
  HulyComponents,
  HulyIssueTemplates,
  HulyIssuePreview,
  HulyTimeReports,
  HulyCreateProject,
  HulyThread,
  HulyActivity,
  HulyCalendar,
  HulyBoard,
  HulyDepartmentStaff,
  HulyTodos,
  HulyMyLeads,
  HulyApplications,
} from '@huly-embed/react';

type MoreView =
  | 'my-issues' | 'board' | 'milestones' | 'milestone-detail'
  | 'components' | 'issue-templates' | 'issue-preview' | 'time-reports'
  | 'create-project' | 'thread' | 'activity' | 'calendar'
  | 'department-staff' | 'todos' | 'my-leads' | 'applications';

const VIEWS: { value: MoreView; label: string }[] = [
  { value: 'my-issues', label: 'My Issues' },
  { value: 'board', label: 'Board' },
  { value: 'milestones', label: 'Milestones' },
  { value: 'milestone-detail', label: 'Milestone Detail' },
  { value: 'components', label: 'Components' },
  { value: 'issue-templates', label: 'Issue Templates' },
  { value: 'issue-preview', label: 'Issue Preview' },
  { value: 'time-reports', label: 'Time Reports' },
  { value: 'create-project', label: 'Create Project' },
  { value: 'thread', label: 'Thread' },
  { value: 'activity', label: 'Activity' },
  { value: 'calendar', label: 'Calendar' },
  { value: 'department-staff', label: 'Department Staff' },
  { value: 'todos', label: 'Todos' },
  { value: 'my-leads', label: 'My Leads' },
  { value: 'applications', label: 'Applications' },
];

interface Props {
  project?: string;
  externalUser?: string;
  onEvent: (message: string) => void;
}

export function MoreDemo({ project, externalUser, onEvent }: Props) {
  const [view, setView] = useState<MoreView>('my-issues');
  const [entityId, setEntityId] = useState('');

  const needsId = ['milestone-detail', 'issue-preview', 'time-reports', 'thread', 'activity', 'department-staff'].includes(view);
  const idLabel: Record<string, string> = {
    'milestone-detail': 'Milestone ID',
    'issue-preview': 'Issue ID',
    'time-reports': 'Issue ID',
    'thread': 'Thread ID',
    'activity': 'Issue ID',
    'department-staff': 'Department ID',
  };

  const loadingEl = <div className="loading-text">Loading {view}...</div>;
  const errorEl = <div className="error-text">Failed to load.</div>;
  const emptyEl = <div className="empty-state">Enter {idLabel[view]} above.</div>;
  const shared = { externalUser, onReady: () => onEvent(`${view}: ready`), onError: (e: { reason: string }) => onEvent(`error: ${e.reason}`), loadingContent: loadingEl, errorContent: errorEl };

  return (
    <div className="demo-section">
      <div className="demo-section-header">
        <h2>More Components</h2>
      </div>
      <div className="demo-controls">
        <span className="demo-controls-label">Component</span>
        <select value={view} onChange={(e) => { setView(e.target.value as MoreView); setEntityId(''); }}>
          {VIEWS.map((v) => (
            <option key={v.value} value={v.value}>{v.label}</option>
          ))}
        </select>
        {needsId && (
          <>
            <span className="demo-controls-label">{idLabel[view]}</span>
            <input
              type="text"
              value={entityId}
              onChange={(e) => setEntityId(e.target.value)}
              placeholder="Enter ID"
            />
          </>
        )}
      </div>
      <div className="embed-container">
        {view === 'my-issues' && <HulyMyIssues project={project} {...shared} onIssueSelected={(e) => onEvent(`issue-selected: ${e.identifier}`)} />}
        {view === 'board' && <HulyBoard {...shared} onIssueSelected={(e) => onEvent(`board issue-selected: ${e.identifier}`)} />}
        {view === 'milestones' && <HulyMilestones project={project} {...shared} />}
        {view === 'milestone-detail' && (entityId ? <HulyMilestoneDetail milestoneId={entityId} {...shared} /> : emptyEl)}
        {view === 'components' && <HulyComponents project={project} {...shared} />}
        {view === 'issue-templates' && <HulyIssueTemplates project={project} {...shared} />}
        {view === 'issue-preview' && (entityId ? <HulyIssuePreview issueId={entityId} {...shared} /> : emptyEl)}
        {view === 'time-reports' && (entityId ? <HulyTimeReports issueId={entityId} {...shared} /> : emptyEl)}
        {view === 'create-project' && <HulyCreateProject {...shared} />}
        {view === 'thread' && (entityId ? <HulyThread threadId={entityId} {...shared} /> : emptyEl)}
        {view === 'activity' && (entityId ? <HulyActivity issueId={entityId} {...shared} /> : emptyEl)}
        {view === 'calendar' && <HulyCalendar {...shared} />}
        {view === 'department-staff' && (entityId ? <HulyDepartmentStaff departmentId={entityId} {...shared} /> : emptyEl)}
        {view === 'todos' && <HulyTodos {...shared} />}
        {view === 'my-leads' && <HulyMyLeads {...shared} />}
        {view === 'applications' && <HulyApplications {...shared} />}
      </div>
    </div>
  );
}
