// examples/react-demo/src/components/DriveDemo.tsx
import { useState } from 'react';
import { HulyFileBrowser, HulyFileDetail } from '@huly-embed/react';

type DriveView = 'file-browser' | 'file-detail';

interface Props {
  externalUser?: string;
  onEvent: (message: string) => void;
}

export function DriveDemo({ externalUser, onEvent }: Props) {
  const [view, setView] = useState<DriveView>('file-browser');
  const [fileId, setFileId] = useState('');
  const [drive, setDrive] = useState('');

  return (
    <div className="demo-section">
      <div className="demo-section-header">
        <h2>Drive</h2>
      </div>
      <div className="demo-controls">
        <span className="demo-controls-label">View</span>
        <select value={view} onChange={(e) => setView(e.target.value as DriveView)}>
          <option value="file-browser">File Browser</option>
          <option value="file-detail">File Detail</option>
        </select>
        {view === 'file-browser' && (
          <>
            <span className="demo-controls-label">Drive</span>
            <input
              type="text"
              value={drive}
              onChange={(e) => setDrive(e.target.value)}
              placeholder="optional"
            />
          </>
        )}
        {view === 'file-detail' && (
          <>
            <span className="demo-controls-label">File ID</span>
            <input
              type="text"
              value={fileId}
              onChange={(e) => setFileId(e.target.value)}
              placeholder="file-id"
            />
          </>
        )}
      </div>
      <div className="embed-container">
        {view === 'file-browser' && (
          <HulyFileBrowser
            drive={drive || undefined}
            externalUser={externalUser}
            onReady={() => onEvent('file-browser: ready')}
            onFileSelected={(e) => onEvent(`file-selected: ${e.fileId}`)}
            onError={(e) => onEvent(`error: ${e.reason}`)}
            loadingContent={<div className="loading-text">Loading file browser...</div>}
            errorContent={<div className="error-text">Failed to load.</div>}
          />
        )}
        {view === 'file-detail' && (
          fileId ? (
            <HulyFileDetail
              fileId={fileId}
              externalUser={externalUser}
              onReady={() => onEvent(`file-detail: ready (${fileId})`)}
              onError={(e) => onEvent(`error: ${e.reason}`)}
              loadingContent={<div className="loading-text">Loading file detail...</div>}
              errorContent={<div className="error-text">Failed to load.</div>}
            />
          ) : (
            <div className="empty-state">Enter a file ID above.</div>
          )
        )}
      </div>
    </div>
  );
}

// examples/angular-demo/src/app/components/drive-demo.component.ts
import { Component, Input, Output, EventEmitter, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HulyFileBrowserComponent, HulyFileDetailComponent } from '@huly-embed/angular';

type DriveView = 'file-browser' | 'file-detail';

@Component({
  selector: 'app-drive-demo',
  standalone: true,
  imports: [FormsModule, HulyFileBrowserComponent, HulyFileDetailComponent],
  template: `
    <div class="demo-section">
      <div class="demo-section-header">
        <h2>Drive</h2>
      </div>
      <div class="demo-controls">
        <span class="demo-controls-label">View</span>
        <select [ngModel]="view()" (ngModelChange)="view.set($event)">
          <option value="file-browser">File Browser</option>
          <option value="file-detail">File Detail</option>
        </select>
        @if (view() === 'file-browser') {
          <span class="demo-controls-label">Drive</span>
          <input
            type="text"
            [ngModel]="drive()"
            (ngModelChange)="drive.set($event)"
            placeholder="optional"
          />
        }
        @if (view() === 'file-detail') {
          <span class="demo-controls-label">File ID</span>
          <input
            type="text"
            [ngModel]="inputValue()"
            (ngModelChange)="inputValue.set($event)"
            (keydown.enter)="loadFile()"
            placeholder="file-id"
          />
          <button class="load-btn" (click)="loadFile()">Load</button>
        }
      </div>
      <div class="embed-container">
        @switch (view()) {
          @case ('file-browser') {
            <huly-file-browser
              [drive]="drive() || undefined"
              [externalUser]="externalUser"
              (fileSelected)="event.emit('file-selected: ' + $event.fileId)"
            ></huly-file-browser>
          }
          @case ('file-detail') {
            @if (fileId()) {
              <huly-file-detail
                [fileId]="fileId()"
                [externalUser]="externalUser"
              ></huly-file-detail>
            } @else {
              <div class="empty-state">Enter a file ID above and click Load.</div>
            }
          }
        }
      </div>
    </div>
  `,
})
export class DriveDemoComponent {
  @Input() externalUser?: string;
  @Output() event = new EventEmitter<string>();

  view = signal<DriveView>('file-browser');
  inputValue = signal('');
  fileId = signal('');
  drive = signal('');

  loadFile() {
    const value = this.inputValue().trim();
    if (value) this.fileId.set(value);
  }
}
