// examples/react-demo/src/components/EventLog.tsx
import type { LogEntry } from '../App';

interface EventLogProps {
  logs: LogEntry[];
  onClear: () => void;
}

export function EventLog({ logs, onClear }: EventLogProps) {
  return (
    <div className="event-log">
      <div className="event-log-header">
        <h3>Event Log</h3>
        <button className="clear-btn" onClick={onClear}>Clear</button>
      </div>
      <div className="log-entries">
        {logs.length === 0 && (
          <div className="log-empty">No events yet</div>
        )}
        {logs.map((entry, i) => (
          <div key={i} className="log-entry">
            <span className="log-time">{entry.time}</span>
            <span className="log-message">{entry.message}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// examples/angular-demo/src/app/components/event-log.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-event-log',
  standalone: true,
  template: `
    <div class="event-log">
      <div class="event-log-header">
        <h3>Event Log</h3>
        <button class="clear-btn" (click)="clear.emit()">Clear</button>
      </div>
      <div class="log-entries">
        @if (logs.length === 0) {
          <div class="log-empty">No events yet</div>
        }
        @for (entry of logs; track $index) {
          <div class="log-entry">
            <span class="log-time">{{ entry.time }}</span>
            <span class="log-message">{{ entry.message }}</span>
          </div>
        }
      </div>
    </div>
  `,
})
export class EventLogComponent {
  @Input() logs: { time: string; message: string }[] = [];
  @Output() clear = new EventEmitter<void>();
}
