// examples/react-demo/src/components/IssueListDemo.tsx
import { HulyIssueList } from '@huly-embed/react';

interface Props {
  project?: string;
  externalUser?: string;
  onEvent: (message: string) => void;
}

export function IssueListDemo({ project, externalUser, onEvent }: Props) {
  return (
    <div className="demo-section">
      <div className="demo-section-header">
        <h2>Issue List</h2>
      </div>
      <div className="embed-container">
        <HulyIssueList
          project={project}
          externalUser={externalUser}
          onReady={() => onEvent('issue-list: ready')}
          onIssueSelected={(e) => onEvent(`issue-selected: ${e.identifier}`)}
          onResize={(e) => onEvent(`issue-list: resize ${e.height}px`)}
          onError={(e) => onEvent(`error: ${e.reason}`)}
          loadingContent={<div className="loading-text">Loading issue list...</div>}
          errorContent={<div className="error-text">Failed to load. Check backend is running.</div>}
        />
      </div>
    </div>
  );
}

// examples/angular-demo/src/app/components/issue-list-demo.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { HulyIssueListComponent } from '@huly-embed/angular';

@Component({
  selector: 'app-issue-list-demo',
  standalone: true,
  imports: [HulyIssueListComponent],
  template: `
    <div class="demo-section">
      <div class="demo-section-header">
        <h2>Issue List</h2>
      </div>
      <div class="embed-container">
        <huly-issue-list
          [project]="project"
          [externalUser]="externalUser"
          (issueSelected)="event.emit('issue-selected: ' + $event.identifier)"
          (resized)="event.emit('issue-list: resize ' + $event.height + 'px')"
        >
        </huly-issue-list>
      </div>
    </div>
  `,
})
export class IssueListDemoComponent {
  @Input() project?: string;
  @Input() externalUser?: string;
  @Output() event = new EventEmitter<string>();
}
