// examples/react-demo/src/components/KanbanDemo.tsx
import { HulyKanban } from '@huly-embed/react';

interface Props {
  project?: string;
  externalUser?: string;
  onEvent: (message: string) => void;
}

export function KanbanDemo({ project, externalUser, onEvent }: Props) {
  return (
    <div className="demo-section">
      <div className="demo-section-header">
        <h2>Kanban Board</h2>
      </div>
      <div className="embed-container">
        <HulyKanban
          project={project}
          externalUser={externalUser}
          onReady={() => onEvent('kanban: ready')}
          onIssueSelected={(e) => onEvent(`kanban issue-selected: ${e.identifier}`)}
          onResize={(e) => onEvent(`kanban: resize ${e.height}px`)}
          onError={(e) => onEvent(`error: ${e.reason}`)}
          loadingContent={<div className="loading-text">Loading kanban board...</div>}
          errorContent={<div className="error-text">Failed to load. Check backend is running.</div>}
        />
      </div>
    </div>
  );
}

// examples/angular-demo/src/app/components/kanban-demo.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { HulyKanbanComponent } from '@huly-embed/angular';

@Component({
  selector: 'app-kanban-demo',
  standalone: true,
  imports: [HulyKanbanComponent],
  template: `
    <div class="demo-section">
      <div class="demo-section-header">
        <h2>Kanban Board</h2>
      </div>
      <div class="embed-container">
        <huly-kanban
          [project]="project"
          [externalUser]="externalUser"
          (issueSelected)="event.emit('kanban issue-selected: ' + $event.identifier)"
          (resized)="event.emit('kanban: resize ' + $event.height + 'px')"
        >
        </huly-kanban>
      </div>
    </div>
  `,
})
export class KanbanDemoComponent {
  @Input() project?: string;
  @Input() externalUser?: string;
  @Output() event = new EventEmitter<string>();
}
