// examples/angular-demo/src/app/app.component.ts
import { Component, signal, effect } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CreateIssueDemoComponent } from './components/create-issue-demo.component';
import { IssueListDemoComponent } from './components/issue-list-demo.component';
import { IssueDetailDemoComponent } from './components/issue-detail-demo.component';
import { KanbanDemoComponent } from './components/kanban-demo.component';
import { CommentsDemoComponent } from './components/comments-demo.component';
import { DocumentsDemoComponent } from './components/documents-demo.component';
import { DriveDemoComponent } from './components/drive-demo.component';
import { MoreDemoComponent } from './components/more-demo.component';
import { CustomEmbedDemoComponent } from './components/custom-embed-demo.component';
import { EventLogComponent } from './components/event-log.component';

type Tab = 'create-issue' | 'issues' | 'detail' | 'kanban' | 'comments' | 'docs' | 'drive' | 'more' | 'custom';

const STORAGE_KEY = 'huly-demo-state';

function loadPersistedState(): { tab?: Tab; project?: string; externalUser?: string; settingsOpen?: boolean } {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

const _saved = loadPersistedState();

interface LogEntry {
  time: string;
  message: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    FormsModule,
    CreateIssueDemoComponent,
    IssueListDemoComponent,
    IssueDetailDemoComponent,
    KanbanDemoComponent,
    CommentsDemoComponent,
    DocumentsDemoComponent,
    DriveDemoComponent,
    MoreDemoComponent,
    CustomEmbedDemoComponent,
    EventLogComponent,
  ],
  template: `
    <div class="app">
      <header class="app-header">
        <div class="header-brand">
          <div class="header-logo">H</div>
          <h1>Huly Embed <span>Angular Demo</span></h1>
        </div>
        <button class="settings-toggle" (click)="settingsOpen.set(!settingsOpen())">
          <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5">
            <circle cx="8" cy="8" r="2.5"/>
            <path d="M8 1v2M8 13v2M1 8h2M13 8h2M3.05 3.05l1.41 1.41M11.54 11.54l1.41 1.41M3.05 12.95l1.41-1.41M11.54 4.46l1.41-1.41"/>
          </svg>
          Settings
        </button>
      </header>

      <nav class="tabs">
        @for (tab of tabs; track tab.id; let i = $index) {
          @if (i === 5) {
            <div class="tab-separator"></div>
          }
          <button
            class="tab"
            [class.active]="activeTab() === tab.id"
            (click)="activeTab.set(tab.id)"
          >
            {{ tab.label }}
          </button>
        }
      </nav>

      <div class="main-content">
        <div class="content-area">
          @if (settingsOpen()) {
            <div class="settings-panel">
              <h3>Configuration</h3>
              <div class="settings-grid">
                <label>
                  Project
                  <input
                    type="text"
                    [ngModel]="project()"
                    (ngModelChange)="project.set($event)"
                    placeholder="Override defaultProject"
                  />
                </label>
                <label>
                  External User
                  <input
                    type="text"
                    [ngModel]="externalUser()"
                    (ngModelChange)="externalUser.set($event)"
                    placeholder="user@example.com"
                  />
                </label>
              </div>
            </div>
          }

          <div class="component-area">
            @switch (activeTab()) {
              @case ('create-issue') {
                <app-create-issue-demo
                  [project]="project() || undefined"
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
              @case ('issues') {
                <app-issue-list-demo
                  [project]="project() || undefined"
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
              @case ('detail') {
                <app-issue-detail-demo
                  [project]="project() || undefined"
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
              @case ('kanban') {
                <app-kanban-demo
                  [project]="project() || undefined"
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
              @case ('comments') {
                <app-comments-demo
                  [project]="project() || undefined"
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
              @case ('docs') {
                <app-documents-demo
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
              @case ('drive') {
                <app-drive-demo
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
              @case ('more') {
                <app-more-demo
                  [project]="project() || undefined"
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
              @case ('custom') {
                <app-custom-embed-demo
                  [project]="project() || undefined"
                  [externalUser]="externalUser() || undefined"
                  (event)="addLog($event)"
                />
              }
            }
          </div>
        </div>

        <app-event-log [logs]="logs()" (clear)="clearLogs()" />
      </div>
    </div>
  `,
})
export class AppComponent {
  tabs = [
    { id: 'create-issue' as Tab, label: 'Create Issue' },
    { id: 'issues' as Tab, label: 'Issues' },
    { id: 'detail' as Tab, label: 'Detail' },
    { id: 'kanban' as Tab, label: 'Kanban' },
    { id: 'comments' as Tab, label: 'Comments' },
    { id: 'docs' as Tab, label: 'Docs' },
    { id: 'drive' as Tab, label: 'Drive' },
    { id: 'more' as Tab, label: 'More' },
    { id: 'custom' as Tab, label: 'Custom' },
  ];

  activeTab = signal<Tab>(_saved.tab ?? 'create-issue');
  settingsOpen = signal(_saved.settingsOpen ?? false);
  project = signal(_saved.project ?? '');
  externalUser = signal(_saved.externalUser ?? '');
  logs = signal<LogEntry[]>([]);

  constructor() {
    effect(() => {
      localStorage.setItem(STORAGE_KEY, JSON.stringify({
        tab: this.activeTab(),
        project: this.project(),
        externalUser: this.externalUser(),
        settingsOpen: this.settingsOpen(),
      }));
    });
  }

  addLog(message: string) {
    const now = new Date();
    const time = now.toLocaleTimeString('en-US', { hour12: false });
    this.logs.update((prev) => [{ time, message }, ...prev]);
  }

  clearLogs() {
    this.logs.set([]);
  }
}

// examples/react-demo/src/App.tsx
import { useState, useCallback, useEffect } from 'react';
import { CreateIssueDemo } from './components/CreateIssueDemo';
import { IssueListDemo } from './components/IssueListDemo';
import { IssueDetailDemo } from './components/IssueDetailDemo';
import { KanbanDemo } from './components/KanbanDemo';
import { CommentsDemo } from './components/CommentsDemo';
import { DocumentsDemo } from './components/DocumentsDemo';
import { DriveDemo } from './components/DriveDemo';
import { MoreDemo } from './components/MoreDemo';
import { CustomEmbedDemo } from './components/CustomEmbedDemo';
import { EventLog } from './components/EventLog';

type Tab = 'create-issue' | 'issues' | 'detail' | 'kanban' | 'comments' | 'docs' | 'drive' | 'more' | 'custom';

const STORAGE_KEY = 'huly-demo-state';

function loadPersistedState(): { tab?: Tab; project?: string; externalUser?: string; settingsOpen?: boolean } {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

const TABS: { id: Tab; label: string }[] = [
  { id: 'create-issue', label: 'Create Issue' },
  { id: 'issues', label: 'Issues' },
  { id: 'detail', label: 'Detail' },
  { id: 'kanban', label: 'Kanban' },
  { id: 'comments', label: 'Comments' },
  { id: 'docs', label: 'Docs' },
  { id: 'drive', label: 'Drive' },
  { id: 'more', label: 'More' },
  { id: 'custom', label: 'Custom' },
];

export interface LogEntry {
  time: string;
  message: string;
}

export function App() {
  const saved = loadPersistedState();
  const [activeTab, setActiveTab] = useState<Tab>(saved.tab ?? 'create-issue');
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [project, setProject] = useState(saved.project ?? '');
  const [externalUser, setExternalUser] = useState(saved.externalUser ?? '');
  const [settingsOpen, setSettingsOpen] = useState(saved.settingsOpen ?? false);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ tab: activeTab, project, externalUser, settingsOpen }));
  }, [activeTab, project, externalUser, settingsOpen]);

  const addLog = useCallback((message: string) => {
    const now = new Date();
    const time = now.toLocaleTimeString('en-US', { hour12: false });
    setLogs((prev) => [{ time, message }, ...prev]);
  }, []);

  const clearLogs = useCallback(() => setLogs([]), []);

  const sharedProps = {
    project: project || undefined,
    externalUser: externalUser || undefined,
    onEvent: addLog,
  };

  return (
    <div className="app">
      <header className="app-header">
        <div className="header-brand">
          <div className="header-logo">H</div>
          <h1>Huly Embed <span>React Demo</span></h1>
        </div>
        <button
          className="settings-toggle"
          onClick={() => setSettingsOpen(!settingsOpen)}
        >
          <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5">
            <circle cx="8" cy="8" r="2.5"/>
            <path d="M8 1v2M8 13v2M1 8h2M13 8h2M3.05 3.05l1.41 1.41M11.54 11.54l1.41 1.41M3.05 12.95l1.41-1.41M11.54 4.46l1.41-1.41"/>
          </svg>
          Settings
        </button>
      </header>

      <nav className="tabs">
        {TABS.map((tab, i) => (
          <span key={tab.id} style={{ display: 'contents' }}>
            {i === 5 && <div className="tab-separator" />}
            <button
              className={`tab ${activeTab === tab.id ? 'active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
            >
              {tab.label}
            </button>
          </span>
        ))}
      </nav>

      <div className="main-content">
        <div className="content-area">
          {settingsOpen && (
            <div className="settings-panel">
              <h3>Configuration</h3>
              <div className="settings-grid">
                <label>
                  Project
                  <input
                    type="text"
                    value={project}
                    onChange={(e) => setProject(e.target.value)}
                    placeholder="Override defaultProject"
                  />
                </label>
                <label>
                  External User
                  <input
                    type="text"
                    value={externalUser}
                    onChange={(e) => setExternalUser(e.target.value)}
                    placeholder="user@example.com"
                  />
                </label>
              </div>
            </div>
          )}

          <div className="component-area">
            {activeTab === 'create-issue' && <CreateIssueDemo {...sharedProps} />}
            {activeTab === 'issues' && <IssueListDemo {...sharedProps} />}
            {activeTab === 'detail' && <IssueDetailDemo {...sharedProps} />}
            {activeTab === 'kanban' && <KanbanDemo {...sharedProps} />}
            {activeTab === 'comments' && <CommentsDemo {...sharedProps} />}
            {activeTab === 'docs' && <DocumentsDemo externalUser={sharedProps.externalUser} onEvent={addLog} />}
            {activeTab === 'drive' && <DriveDemo externalUser={sharedProps.externalUser} onEvent={addLog} />}
            {activeTab === 'more' && <MoreDemo {...sharedProps} />}
            {activeTab === 'custom' && <CustomEmbedDemo {...sharedProps} />}
          </div>
        </div>

        <EventLog logs={logs} onClear={clearLogs} />
      </div>
    </div>
  );
}
