// packages/react/src/components/HulyCreateIssue.tsx
import type { HulyIssueCreatedEvent, HulyIssueCancelledEvent } from '@huly-embed/core';
import { HulyEmbed, type HulyEmbedProps } from './HulyEmbed.js';

export interface HulyCreateIssueProps
  extends Pick<HulyEmbedProps, 'project' | 'externalUser' | 'hideFields' | 'loadingContent' | 'errorContent' | 'onReady' | 'onError'> {
  onIssueCreated?: (event: HulyIssueCreatedEvent) => void;
  onIssueCancelled?: (event: HulyIssueCancelledEvent) => void;
}

export function HulyCreateIssue({ onIssueCreated, onIssueCancelled, ...rest }: HulyCreateIssueProps) {
  return (
    <HulyEmbed
      component="create-issue"
      onIssueCreated={onIssueCreated}
      onIssueCancelled={onIssueCancelled}
      {...rest}
    />
  );
}

// packages/angular/src/lib/components/huly-create-issue.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import type { HulyIssueCreatedEvent, HulyIssueCancelledEvent, EmbedHideableField } from '@huly-embed/core';
import { HulyEmbedComponent } from './huly-embed.component';

@Component({
  selector: 'huly-create-issue',
  standalone: true,
  imports: [HulyEmbedComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <huly-embed
      component="create-issue"
      [project]="project"
      [externalUser]="externalUser"
      [hideFields]="hideFields"
      (issueCreated)="issueCreated.emit($event)"
      (issueCancelled)="issueCancelled.emit($event)"
    >
      <ng-content select="[loading]" loading></ng-content>
      <ng-content select="[error]" error></ng-content>
    </huly-embed>
  `,
})
export class HulyCreateIssueComponent {
  @Input() project?: string;
  @Input() externalUser?: string;
  @Input() hideFields?: EmbedHideableField[];

  @Output() readonly issueCreated = new EventEmitter<HulyIssueCreatedEvent>();
  @Output() readonly issueCancelled = new EventEmitter<HulyIssueCancelledEvent>();
}
